export const CURRENT_CLIENT = "CURRENT_CLIENT";
export const CLIENT_JOB_SELECTED = "CLIENT_JOB_SELECTED";
export const CLIENT_JOB_CREATED = "CLIENT_JOB_CREATED";
export const CLIENT_JOB_UPDATED = "CLIENT_JOB_UPDATED";
export const CURRENT_CONTRACTOR = "CURRENT_CONTRACTOR";
export const CONTRACTOR_JOBS = "CONTRACTOR_JOBS";
export const CONTRACTOR_JOB_SELECTED = "CONTRACTOR_JOB_SELECTED";
export const CONTRACTOR_JOB_QUOTE_UPDATE = "CONTRACTOR_JOB_QUOTE_UPDATE";
export const CONTRACTOR_MAP_CLIENT_SELECTED = "CONTRACTOR_CLIENT_SELECTED";
export const CONTRACTOR_MAP_JOB_QUOTE_UPDATE = "CONTRACTOR_MAP_JOB_QUOTE_UPDATE";
export const CONTRACTOR_MAP_JOB_QUOTE_CREATED = "CONTRACTOR_MAP_JOB_QUOTE_UPDATE";
export const CONTRACTOR_MAP_JOB_SELECTED = "CONTRACTOR_MAP_JOB_SELECTED";

