export const CURRENT_CLIENT = "CURRENT_CLIENT";
export const CURRENT_CONTRACTOR = "CURRENT_CONTRACTOR";
export const CONTRACTOR_JOBS = "CONTRACTOR_JOBS";
export const CONTRACTOR_JOB_SELECTED = "CONTRACTOR_JOB_SELECTED";
export const CONTRACTOR_JOB_QUOTE_UPDATE = "CONTRACTOR_JOB_QUOTE_UPDATE";

